
- name: install apache2 and php package(Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - {{ apache_package_name }}
      - {{ php_package_name }}
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: install apache2 and php package (CentOs)
  tags: apache,httpd,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOs"

- name: start Httpd (CentOs)
  tags: apache,httpd,centos,start
  service: 
    name: httpd
    state: started
    enabled: yes 
  when: ansible_distribution == "CentOs"
  register: httpd

- name: restrt httpd(CentOs)
  tags: apache,httpd,centos,start
  service: 
    name: httpd
    state: restarted
  when: httpd.changed
- name: restrt apache2(Ubuntu)
  tags: apache,httpd,centos,start
  service: 
    name: {{ apache2 }}
    state: restarted
  when: ansible_distribution == "Ubuntu"
- name: change email address for admin 
  tags: apache,apache2,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServiceAdmin'
    line : ServiceAdmin somebody@somecomro.net
  when: ansible_distribution == "CentOs"

- name: Copy file
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

