---
- hosts: all
  become: true
  tasks:
    - name: install apache and php package
      apt:
        update_cache: yes
        name: 
          - "{{ apache_package }}"
          - "{{ php }}"
        state: latest
