---
- hosts: all
  become: true
  tasks:
    - name: remove packages
      apt:
        name: 
          - apache2
          - libapache2-mod-php
          - mariadb-server
          - samba
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: remove packages
      dnf:
        name:
          - httpd
          - php
          - mariadb
          - samba
        state: absent
      when: ansible_distribution == "CentOs"