---
- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes
    - name: install apache2 and php package
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: absent

    - name: update repository index
      dnf:
        update_cache: yes
      when: ansible_distribution == "CentOs"
    - name: install apache2 and php package
      dnf:
        name:
          - httpd
          - php
        state: absent
      when: ansible_distribution == "CentOs"
