---
- hosts: all
  become: true
  tasks:
    - name: remove apache2 and php package
      apt:
        update_cache: yes
        name: 
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: remove apache2 and php package
        dnf:
        update_cache: yes
          name:
            - httpd
            - php
          state: absent
        when: ansible_distribution == "CentOs"
