---
- hosts: all
  become: true
  tasks:
    - name: remove apache2 and php package
      package:
        update_cache: yes
        name: 
          - "{{ apache_package }}"
          - "{{ php }}"
        state: absent

