---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOs)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOs"
    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  
    - name: install apache2 and php package(Ubuntu)
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 and php package (CentOs)
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOs"
      
- hosts: db_servers
  become: true
  tasks:
  
    - name: install mariadb package(Ubuntu)
      apt:
        name: 
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb(CentOs)
      dnf:
        name:
          - mariadb
        state: latest
      when: ansible_distribution == "CentOs"