---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOs)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOs"
    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2 and php package(Ubuntu)
      tags: apache,apache2,ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"


    - name: install apache2 and php package (CentOs)
      tags: apache,httpd,centos
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOs"

    - name: start Httpd (CentOs)
      tags: apache,httpd,centos,start
      service: 
        name: httpd
        state: started
        enabled: yes 
      when: ansible_distribution == "CentOs"
      register: httpd

    - name: restrt httpd(CentOs)
      tags: apache,httpd,centos,start
      service: 
        name: httpd
        state: restarted
      when: httpd.changed

    - name: change email address for admin 
      tags: apache,apache2,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServiceAdmin'
        line : ServiceAdmin somebody@somecomro.net
      when: ansible_distribution == "CentOs"

    - name: Copy file
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package(Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
        name: 
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb(CentOs)
      tags: centos,db,mariadb
      dnf:
        name:
          - mariadb
        state: latest
      when: ansible_distribution == "CentOs"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: 
          - samba
        state: latest

- hosts: all
  become: true
  tasks:
    - name: create simone user
      tags: alwaysa
      user:
        name: simone
        group: root

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: 
          - unzip
        state: latest
    - name: install teraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_386.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
