---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOs)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOs"
    - name: install updates (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  role: webservice  
- hosts: db_servers
  become: true
  role: dbservice

- hosts: file_servers
  become: true
  role: fileservice
- hosts: all
  become: true
  role: base

- hosts: workstations
  become: true
  role: workservice