- name: install mariadb package(Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: 
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb(CentOs)
  tags: centos,db,mariadb
  dnf:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOs"
