
- name: install unzip
  package:
    name: 
      - unzip
    state: latest
- name: install teraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_386.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
